package com.mattharrah.gedcom4j;

public enum FamilyEventType {
	ANNULMENT, CENSUS, DIVORCE, DIVORCE_FILED, ENGAGEMENT, MARRIAGE, MARRIAGE_BANNER, MARRIAGE_CONTRACT, MARRIAGE_LICENSE, MARRIAGE_SETTLEMENT, EVENT
}
