package com.mattharrah.gedcom4j;

public enum IndividualEventType {
	ADOPTION, BIRTH, BAPTISM, BAR_MITZVAH, BAS_MITZVAH, BLESSING, BURIAL, CENSUS, CHRISTENING, CHRISTENING_ADULT, CONFIRMATION, CREMATION, DEATH, EMIGRATION, FIRST_COMMUNION, GRADUATION, IMMIGRATION, NATURALIZATION, ORDINATION, RETIREMENT, PROBATE, WILL, EVENT
}
