package com.mattharrah.gedcom4j;

public enum IndividualAttributeType {
	CASTE_NAME, PHYSICAL_DESCRIPTION, SCHOLASTIC_ACHIEVEMENT, NATIONAL_ID_NUMBER, NATIONAL_OR_TRIBAL_ORIGIN, COUNT_OF_CHILDREN, COUNT_OF_MARRIAGES, OCCUPATION, POSSESSIONS, RELIGIOUS_AFFILIATION, RESIDENCE, SOCIAL_SECURITY_NUMBER, NOBILITY_TYPE_TITLE
}
